# Generated by Django 5.0.6 on 2024-07-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nuevo_proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.TextField(max_length=50)),
                ('profesor', models.TextField(max_length=50, null=True)),
                ('proy', models.TextField(max_length=255)),
                ('tema', models.TextField(max_length=50)),
            ],
        ),
    ]
