# Generated by Django 5.0.6 on 2024-07-06 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('PRG', 'Código PRG'), ('PRD', 'Código PRD'), ('PRA', 'Código PRA')], default='-', max_length=3)),
                ('litros', models.IntegerField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('turno', models.CharField(max_length=2)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
