# Generated by Django 5.0.6 on 2024-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='codigo',
            field=models.CharField(choices=[('PRG', 'PRG'), ('PRD', 'PRD'), ('PRA', 'PRA')], default='-', max_length=3),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='turno',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM'), ('MM', 'MM')], default='-', max_length=2),
        ),
    ]
