# Generated by Django 5.0.6 on 2024-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_combustible_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
